### ISSUE TITLE
Harmonization of file formats (plot download)

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#1]
When we download a file from a plot, e.g. 
[https://dgrpool.epfl.ch/phenotypes/1643](https://dgrpool.epfl.ch/phenotypes/1643)
Then clicking on the Data button within the plot cards

The format of the files are different. Especially the data header and column order should be uniformized within the app.

I would suggest taking the same requirements that we ask for in the ["Check your phenotype"](https://dgrpool.epfl.ch/check_pheno) tool, i.e.
**DGRP**\t**sex**\t**pheno_name**      as header, and for column order

This would also allow users to download data and submit to the GWAS tool, if they aim at repeating a GWAS calculation, without modifying the files.

In particular, the "distri_plot" misses the **DGRP** column, and the sexes are encoded 1 for M (we should stick to M)

Other plots output should be checked as well (boxplots) see [https://dgrpool.epfl.ch/phenotypes/2636](https://dgrpool.epfl.ch/phenotypes/2636)

**Comment by fab-dav** [comment]
Unfortunately this is not possible for these specific Data buttons. Here it's a generic implementation that allows to download the data visible on the plot. Anyway, I think what you need, and which is missing on this page, is a button to dowload the actually data in a tabular format (following the format you describe) and containing all the data together (M, F and NA). I can also add a button to access the data + metadata for this specific phenotype in JSON as a API access.

**Comment by VincentGardeux** [comment]
This is not true.
I've done it for the Boxplots in the GWAS results. I've created a button to download the HTML and another one to download the data as TSV.

But it's ok to have another button like the ones you did in the header of the plots I guess.

I also like the idea of the JSON for API access

**Comment by fab-dav** [comment]
I've added :
-the links to download the data (original and summary if original data are by sample/raw) in a new section.
-a link to get the data programmatically all data in JSON format for a specific phenotype

**Comment by VincentGardeux** [comment]
There is still a problem:
- Files are dowloaded but are named "download" could you make it with a better name, matching hte phenotype?
- The DGRP column is called "DGRP line" instead of "DGRP"

**Comment by fab-dav** [comment]
I think this is fixed now then.
