### ISSUE TITLE
Check your phenotype tool -> Upload button

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#10]
This button seems irrelevant, and a bit counterintuitive.
For e.g. if we are already analyzing a dataset, and we submit another one, we still see the results of the previous one, until we press "Upload". Which may be confusing
=> One may think that it's recomputed already

Is this button really useful? We could simply remove it and perform an automatic submit when a file is changed in the Browse part?

**Comment by fab-dav** [comment]
The button comes with the file_field widget. I cannot remove it. However now I hide the upload part when it's done, and add a restart button to analyze another file. Added a check to avoid uploading if a file has not been selected + alert message. I think it should be ok like this.
