### ISSUE TITLE
Issue with downloading boxplots, when large number of lines

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#11]
We should adapt the width of the downloaded boxplot according to the number of DGRP lines (only for boxplot on raw data?)
For example: [https://dgrpool.epfl.ch/phenotypes/2858](https://dgrpool.epfl.ch/phenotypes/2858) third plot in PNG/SVG is not readable.

**Comment by fab-dav** [comment]
I think this is a duplicated issue. It's already solved.

**Comment by VincentGardeux** [comment]
The SVG export is nice, but the PNG export is a bit too wide.
Please check [http://biccsrv3.epfl.ch:32786/phenotypes/2797](http://biccsrv3.epfl.ch:32786/phenotypes/2797) or [http://biccsrv3.epfl.ch:32786/phenotypes/2858](http://biccsrv3.epfl.ch:32786/phenotypes/2858)

**Comment by fab-dav** [comment]
Impossible to handle better the PNG export. What matters anyway is the SVG one, and I would be in favor to simply remove the PNG one because it's useless.

**Comment by VincentGardeux** [comment]
Ok we'll keep it as is
