### ISSUE TITLE
DGRP lines in ordered barplots and boxplots

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#12]
In [https://dgrpool.epfl.ch/phenotypes/2858](https://dgrpool.epfl.ch/phenotypes/2858) the 3rd and 4th plots (boxplot and barplot) contain many many DGRP lines. 
However, only a few of them are displayed in X labels.

It probably "jumps" some lines to enhance the visibility. But it may make a lay user to wrongly order the lines.

We should whether display all the DGRP lines, or not display them at all?

**Comment by fab-dav** [comment]
It's a default behaviour of Plotly. However, I understand this concern, so not it's not displaying anymore the x-axis labels if there are too many dgrp lines for the page width.

**Comment by fab-dav** [comment]
Finally, it's not ok, because we still want to have the labels for the exports as static images. So I try to force the display to every bar / boxplot and to adjust the size of the font in function of the page width and number of dgrp lines.

**Comment by VincentGardeux** [comment]
Works for now. May be problematic when fixing issue #22
