### ISSUE TITLE
Keeping results in the "Check your phenotype" tool

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#14]
It would be nice if we could have a permalink to be able to access previous results. Or to keep track of results / switch from one result to the other, etc...

Maybe a feature for logged-in users? Or maybe simply provide a permalink on top of the results?
=> Of course this would require more space?

**Comment by fab-dav** [comment]
Done

**Comment by VincentGardeux** [comment]
I don't know if this is this new feature, but the tool is super buggy now.
Keeps swapping from the wheel to finished, to the wheel, etc...
Plus, the history tab is super slow to load?

**Comment by fab-dav** [comment]
As I told you I'm working on it now...
