### ISSUE TITLE
Non-logic separation of the phenotypes by stats (sd, mean, median)

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#16]
Currently, the same phenotype can have multiple stats associated with it (sd, mean, median, se, ...)
However, nothing is currently linking all these stats to the fact that it's the same phenotype. We "just" create one phenotype for each stat
Would be better to have a unique phenotype and different stats on it. Or at least to be able to regroup them on the same phenotype?
This also answers a question from Emily, stating:

> Maybe it would be a bit clearer to just divide the phenotypes by name (eg: “eclosion 5ug toxin” , “eclosion 10ug toxin”) and then when you click on the phenotype you can see the other data that are available (eg: “sd” “sem”)

**Comment by fab-dav** [comment]
I don't really understand. I need more examples. I checked eclosion 5ug toxin and I found only one phenotype that would match: pc_Surv_MeHg_5 (?)

**Comment by VincentGardeux** [comment]
We will not implement that
