### ISSUE TITLE
GWAS "transcript annotation pop up" design

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#17]
Currently, the design of the "transcript annotation" pop up is very limited.
We should make it more appealing? Plots? Colors?

**Comment by fab-dav** [comment]
I don't know what to add. Which plot are you thinking about?

**Comment by VincentGardeux** [comment]
Here are some ideas:
1. We should limit the size of the popup
2. If it's empty (for e.g. Intergenic regions), it should not be clickable?
3. We could add more information about the gene? Links to external DB or to our gene view (open new window)
4. If not 3. we could also provide a summary of what we have in our gene view
5. We could put a JBrowse embedded plot
