### ISSUE TITLE
Make a "PheWAS" button on the top menu

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#19]
Or maybe call it "Variant", since it will be a variant-centric view? To be defined.

It would make a standard PheWAS plot, aggregating the p-values of a particular variant across all phenotypes.
We should be able to search for a variant and get the GWAS results as a standard [PheWAS plot](https://www.researchgate.net/publication/294288300/figure/fig2/AS:330299482361864@1455760941613/A-PheWAS-Manhattan-plot-for-a-given-SNP-This-plot-shows-the-significance-of-association.png)

Ideally, the phenotypes should be sorted by category

**Comment by VincentGardeux** [comment]
This goes along with the variant view we discussed already.
I can write a script in R or Python to run the PheWAS across all phenotypes for a given variant, and preprocess everything?

**Comment by fab-dav** [comment]
Yes, let me know when it's ready
