### ISSUE TITLE
Display of GWAS / Correlation in the phenotype page

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#2]
In the phenotype page of any phenotype e.g. [https://dgrpool.epfl.ch/phenotypes/2636](https://dgrpool.epfl.ch/phenotypes/2636)
The section about the **Analyses** results is not very appealing (two buttons).

Maybe one thing we could do is to add a small clickable vignette with the GWAS plot for the GWAS results? And similarly with the "Compute correlation" button?

I would also change the name "Compute correlation" with something more explicit? Like "Correlation with other phenotypes"?

**Comment by fab-dav** [comment]
I changed the style of the page, replaced the compute correlation button by a Correlation with other phenotypes link. Not sure the vignette would add much and would require to change again the layout of cards. Let me know if it's ok for you like this.

**Comment by VincentGardeux** [comment]
Mmm I'm not super satisfied with this.
It's not very appealing (links). Maybe even less than before. And we don't see very well the link to the GWAS results (that was the main reason behind the idea of a vignette).

**Comment by fab-dav** [comment]
I can add buttons again, but the fact the text is longer will be a little ugly I suppose.
Vignettes would take too much space...

**Comment by VincentGardeux** [comment]
I like the "Analysis" part that you made. But, to better catch the eye, I was thinking of displaying in small something like that:

![image](https://github.com/DeplanckeLab/dgrpool_web/assets/15444333/46a9bbe9-1735-4faf-ad8f-ab51f9689a14)

Ideally I was thinking of the actual plots, but maybe we can make icons, or very small generic plots?

**Comment by VincentGardeux** [comment]
No enhancement for now. We'll see how it's received by users.
