### ISSUE TITLE
Correlation plot in the "Phenotype" page

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#21]
On a phenotype page, we can run "Compute phenotype", which gives a tab of phenotypes correlated with our phenotype of interest.
It would be interesting to have a button to compute the plot of a particular correlation, next to each compared phenotype?

Currently, we can do these plots by going to the Tools>Correlation menu, but it would be better to see it directly within the Phenotype>Correlation menu.

**Comment by fab-dav** [comment]
Done

**Comment by VincentGardeux** [comment]
The tool is not working.
I tested this: http://biccsrv3.epfl.ch:32786/phenotypes/1315/compute_correlation
