### ISSUE TITLE
Resize plots when resizing window

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#22]
Plots should be resized when we change the window size.

**Comment by fab-dav** [comment]
Which plots?

**Comment by VincentGardeux** [comment]
Well all of them no?
The page should adapt to the window size. Thus a redraw should be triggered when we change the window size.

Examples:
- Front page
- Phenotype page (e.g. https://dgrpool.epfl.ch/phenotypes/2635)
- Pheno correlation tool: https://dgrpool.epfl.ch/pheno_correlation

**Comment by fab-dav** [comment]
Done for welcome page, phenotype page, and correlation plots.

**Comment by VincentGardeux** [comment]
The ones in the phenotype page are bugging? That's what we saw together.

**Comment by fab-dav** [comment]
http://biccsrv3.epfl.ch:32786/phenotypes/2620
http://biccsrv3.epfl.ch:32786/phenotypes/2635
http://biccsrv3.epfl.ch:32786/phenotypes/2812
http://biccsrv3.epfl.ch:32786/phenotypes/1312

**Comment by VincentGardeux** [comment]
Celui-ci plante: http://biccsrv3.epfl.ch:32786/phenotypes/2812
