### ISSUE TITLE
Pie charts on front page

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#24]
The pie charts on the front page disappear / are not readable depending on the window size.
Please adapt the UI accordingly, so they stay visible

**Comment by fab-dav** [comment]
I cannot reproduce this problem...

**Comment by VincentGardeux** [comment]
![Sans titre](https://github.com/DeplanckeLab/dgrpool_web/assets/15444333/b11ce2ee-c48d-4ee3-aca1-e33e7b1cd675)

**Comment by VincentGardeux** [comment]
Just reduce the window size and refresh the page

**Comment by fab-dav** [comment]
I think I fixed this issue that was occuring with Chrome

**Comment by VincentGardeux** [comment]
Nope.
You need to refresh the page

![image](https://github.com/DeplanckeLab/dgrpool_web/assets/15444333/b8d1e410-7000-48c4-8432-711e36e86bb2)

**Comment by fab-dav** [comment]
OK, I think this time it's fixed.
