### ISSUE TITLE
Raw data in "Check your phenotype" tool

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#26]
Currently, when a user submit a dataset with raw data (i.e. not summary data, but multiple data points for the same DGRP line), then there is an error message.

Should we instead compute the mean on-the-fly (per sex) and then run the calculations on the mean? (with a warning message)

**Comment by fab-dav** [comment]
done

**Comment by VincentGardeux** [comment]
The warning message can be quite huge. See with this file:
[phenotype_2797_OK_RAW.txt](https://github.com/user-attachments/files/15839121/phenotype_2797_OK_RAW.txt)

Any possibility to make it smaller? Like a pop-up, or just give the number of DGRPs that are duplicated? Or provide the list in the form of a file?

**Comment by fab-dav** [comment]
I'll just add the number of DGRPs if you prefer and only display the list of DGRPs if there are less than 10.

**Comment by fab-dav** [comment]
Done
