### ISSUE TITLE
Nonsensical editable field when editing raw dataset

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#27]
When editing raw phenotypes e.g.
https://dgrpool.epfl.ch/phenotypes/2616/edit

It is possible to set a "summary type"

However, it's a phenotype from a raw dataset. As such it should not have a "summary type" field. Or it should be set to Not applicable and not being editable.
This should be applied for all raw phenotypes

**Comment by fab-dav** [comment]
OK, this is an easy fix as we have a field is_summary to know if the dataset is a summary (one value for each dataset) or a "raw" dataset (multiple values for each dataset). Just adding a condition based on this.

**Comment by fab-dav** [comment]
Done
