### ISSUE TITLE
Phenotype correlation

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#28]
The [https://dgrpool.epfl.ch/pheno_correlation](https://dgrpool.epfl.ch/pheno_correlation) tool could have an improved UI.
Specifically for the sex dropdown list?
Maybe we could by default compute all correlations across sex and with matching sex?
It's a bit weird that, for e.g., when there is only one sex present, it stills picks "matching sex" as default

**Comment by fab-dav** [comment]
I removed the matching sex option if there is only one choice.
