### ISSUE TITLE
Handling of errors in "Check your phenotype"

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#3]
If I submit a wrong phenotype fiile in the "Check your phenotype" tool, like one downloaded from a ordered plot in a phenotype page (phenotype_xxxx_ordered_plot.txt), with this kind of format:
```
trace	x	y
M	DGRP_093	-1.0517896166
```

Then some error messages are nonsense:

> Some DGRP lines are not unique by sex (DGRP_000/NA).
> Please summarize your dataset by DGRP line and sex prior upload.

I guess since DGRP lines are not found, they are all put as NAs?

Next error:

> Not the same number of columns for DGRP DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5),DGRP_000 (5) compared to header (4 column(s)).

Is also probably linked to that?

The main point is, that only the first error message should appear here:

> Header is invalid, first column should be 'DGRP'

This should stop the parsing of the file

**Comment by fab-dav** [comment]
Redundant with #8. Already fixed.

**Comment by VincentGardeux** [comment]
This is not completely fixed yet. As the wrong header should stop the parsing of the file.

**Comment by fab-dav** [comment]
I think this is fixed.
