### ISSUE TITLE
Review 2 - Gene outlinks to Flybase and its genome browser in GWAS results

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#30]
We also agree with both reviewers that gene expression information is of interest. We are committed to enhancing user experience by including more gene-level outlinks to Flybase. Additionally, we will link variants and gene results to Flybase's online genome browser, JBrowse. By following the reviewers' suggestions, we aim to guide DGRPool users to potentially informative genes.
Thus, we have plans to link out to a 'genome browser-like' view (Flybase’s JBrowse tool) of the GWAS results centered around the affected variants/genes. We are considering integrating this feature into the new gene-centric tool as well.

**Comment by VincentGardeux** [comment]
Il faudrait:
- Ajouter un example quand on n'a pas rentré de nom de gène? Genre "Please enter a gene symbol, like ntc, or sima"
- Si on rentre un truc faux, genre "nutcracker" (qui est pas vraiment faux, c'est le long name de ntc, mais bon...) il display quand même une page de résultats vides. Il faudrait mettre que le gène n'est pas trouvé et dire de rentrer le gene symbol, pas le gene name en Hint: 
- Ya toujours le 2 qui tournicote quand ça charge
- Dans la partie "Alleles from flybase" pourquoi les phenotypes mappent sur OLS ontology? Et pas sur Flybase? Genre https://flybase.org/cgi-bin/cvreport.pl?id=FBcv%3A0000374 pour https://www.ebi.ac.uk/ols4/ontologies/fbcv/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FFBcv_0000374. Je pense que c'est plus logique de pointer sur Flybase vu que la section s'appelle "Alleles from Flybase"
- Dans la partie GWAS results, tu peux mettre ce texte, a coté du nombre de résultats? "852 results across all studies at raw p-value < 0.01 cutoff. Note: p-value is not adjusted."
- Dans le tableau des GWAS results. On peut voir le phenotype, mais le nom n'est pas forcément très parlant. On pourrait avoir la même help box que pour transcript annotation, avec le nom complet?

**Comment by fab-dav** [comment]
For point 4, I didn't find a page on flybase, that's why I made a link to OLS. I tried to make a global search with the FBcv identifier and it returns no results.

**Comment by fab-dav** [comment]
For point 5, I apply this also to the analysis tool and GWAS by phenotype?

**Comment by fab-dav** [comment]
For point 4, finally I've found the link, but on flybase the gloabl search tool is not working with FBcv identifiers

**Comment by fab-dav** [comment]
All points done

**Comment by VincentGardeux** [comment]
Update:
- Si on rentre un truc faux, genre "bloblo" il display quand même une page de résultats vides. Il faudrait mettre que le gène n'est pas trouvé
- Dans la GWAS result table, il faudrait mettre Variant ID, Variant type au lieu de SNP, car il y a aussi des indels
- Dans la table "Allele from Flybase" tu pourrais mettre la réference au format citation? (toto et al, 2023) par ex? Mais garder le lien comme tu as fait?
- On pourrait rajouter des liens externes vers les UniprotKB id dans la table ortholog? Ou ça n'existe pas?
- Dans le tableau GWAS results, on pourrait colorer les study par "curated" "under curation", etc.. ? En mettant la légende et en utilisant le même code couleur que dans le reste du site?

**Comment by fab-dav** [comment]
point 1: done; point 2: agreed and done, point 3: I'm not sure I can do this, depends what's in the file., point 4:link added to UniProt and Ensembl in OMA table, point 5: in my opinion, we should display only the studies that are curated, no?

**Comment by fab-dav** [comment]
OK, then after discussion, all points were addressed

**Comment by VincentGardeux** [comment]
Ok everything checked and working.
Only point with reference is not handled but not major atm
