### ISSUE TITLE
Autocomplete in Correlation tool does not work anymore

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#33]
In http://dgrpool.epfl.ch/pheno_correlation

There is no autocomplete anymore?

**Comment by fab-dav** [comment]
You probably broke it with the merge unless something else corrupted the solr folders. After rebuild --no-cache, it's working again on dev and prod. I've re-added the progress-bar gemfile that was also remove after this merge.
