### ISSUE TITLE
Order of DGRP / sex / pheno columns makes tool to bug

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#34]
If I submit a file with the sex column, but not at the second position, it fails with a weird error message

```
Some DGRP lines are not unique by sex (DGRP_703/NA, DGRP_761/NA, [...] .)
Please summarize your dataset by DGRP line and sex prior upload.
```

**Comment by fab-dav** [comment]
It's not really a bug, but due to the fact that if missing in second position, the sex column is automatically added and filled with 'NA'. However, to be more clear, I've added a warning message indicating when the sex column is not found in second position as expected and thus added.
