### ISSUE TITLE
Boxplot in "Check your phenotype" tool

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#36]
The boxplots in the GWAS results are not showing anything

![image](https://github.com/DeplanckeLab/dgrpool_web/assets/15444333/0915eee4-743b-41ed-9859-35573870be05)

**Comment by VincentGardeux** [comment]
[phenotype_1721_ordered_plot_OK.txt](https://github.com/DeplanckeLab/dgrpool_web/files/15305233/phenotype_1721_ordered_plot_OK.txt)

Used this file

**Comment by fab-dav** [comment]
I think I fixed the problem that was occuring with Chrome
