### ISSUE TITLE
Add other info associated to transcripts in SNPs annot_json field

### ISSUE THREAD

**Issue by fab-dav** [DeplanckeLab/dgrpool_web#37]
Should add other information than simply the list of transcripts.
At the moment we collect only the list of transcripts:
 {"transcript_annot":{"UTR_5_PRIME":{"CG43427":["FBtr0308857"]},"INTRON":{"CG43427":["FBtr0
308849","FBtr0308850","FBtr0308851","FBtr0308852","FBtr0308855","FBtr0308856","FBtr0308858"]}},"binding_site_annot":{"transposable_element":{"FlyBase":["FBti0062535"]}}}
instead we can add the position in the transcript and the impact at the level of the transcript.
Then we can display this information in the popup window when clicking a gene/variant impact button in the GWAS table.

**Comment by VincentGardeux** [comment]
Would be super interesting to add the Flybase phenotypes associated with the transcript/gene of a given variant, when clickin on the transcript button

**Comment by VincentGardeux** [comment]
We now link the results to the Gene page
