### ISSUE TITLE
Strange phenotype to check

### ISSUE THREAD

**Issue by fab-dav** [DeplanckeLab/dgrpool_web#38]
http://biccsrv3.epfl.ch:32786/phenotypes/1523
Seems the study is curated but this phenotype seems to have only NAs.
And it seems to be the same for all the other phenotypes for this study.

**Comment by VincentGardeux** [comment]
Mmm no, it's a display error.
There is only NA for female. But for the "undefined sex" there should be values.
Actually, these values are displayed on the summary:

> Only NA values for female.
> Number of mean values for undefined sex: **205**
> Number of mean unique values for undefined sex: **2**

**Comment by fab-dav** [comment]
Ah yes, fixed.
