### ISSUE TITLE
API

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#39]
I like the idea of the API to programmatically download the data (what you did for issue #1 ).
Could you write a new section "API" (with nice icon) on the top bar, and briefly describe what can be downloaded automatically in JSON?

**Comment by fab-dav** [comment]
Don't know which icon to pick in the fontawesome collection for API. Any suggestion?
I wrote the page.

**Comment by VincentGardeux** [comment]
Looks ok as is
