### ISSUE TITLE
GWAS results filtering

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#4]
In the GWAS results pages (both in phenotype and in the "Check your phenotype" tool), it would be interesting to be able to filter the result table by
- Variant impact
- Presence of Binding site annotation / TF name
- Chromosome location (chromosome only, or range)
- Name of gene in which the variants are (transcript annotation column)

This could be done by adding a button with a popup search window on the column header?

**Comment by fab-dav** [comment]
Done

**Comment by VincentGardeux** [comment]
Very nice
