### ISSUE TITLE
Links are dead in phenotype page

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#41]
Some links are dead in the phenotype page.
For e.g., in http://biccsrv3.epfl.ch:32786/phenotypes/2636

The GWAS analysis page is dead?

Also, in this page: http://biccsrv3.epfl.ch:32786/phenotypes/2818
If you click on All data or Original data in the Downloads section, it works.
But the other data don't work (Mean data, ...)

The GWAS page is dead as well there

**Comment by fab-dav** [comment]
first example, GWAS analysis works...(?)
second example is fixed. GWAS analysis works as well
