### ISSUE TITLE
Bug in Check your phenotype tool

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#42]
There is a weird bug in the tool with this file:

[S10_AbdominaPigmentT6_summary_mean.txt](https://github.com/user-attachments/files/15914859/S10_AbdominaPigmentT6_summary_mean.txt)

Which I downloaded from the corresponding dataset (using the new links you created).
It displays immediately a "completed" GWAS. But there is nothing there?
![image](https://github.com/DeplanckeLab/dgrpool_web/assets/15444333/00ae93e2-9b53-4353-9e05-fb337a8d3f04)

BTW, as an external issue. It seems that the "Filter" icon is displaying even if the results are not available:

![image](https://github.com/DeplanckeLab/dgrpool_web/assets/15444333/db88f043-87fe-4398-8903-8bdc5b818125)

**Comment by fab-dav** [comment]
I think something changed in the software output because now it works well, and it was bugging due to the persistance of old results on the server. After deleting the old files and running again the tool, it seems to work.

**Comment by VincentGardeux** [comment]
Ok indeed now it seems to run.
However there is still the error with the Filter button:
![image](https://github.com/DeplanckeLab/dgrpool_web/assets/15444333/b0692a52-9c65-4167-9d86-7d19b165d0b5)

Also, the wheel does not seem to turn anymore?

**Comment by fab-dav** [comment]
Filter not displayed anymore if no results.
Wheel is turning with Firefox and Chrome on my mac...
