### ISSUE TITLE
Filter button is probably misplaced

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#43]
The Filter button in the GWAS results is displayed at the top of the page.
However, it should be displayed in the GWAS results section only. Because the other plots/results are not filtered. Which can be misleading?

**Comment by fab-dav** [comment]
I don't think so, because the number of results is already present in the header of the tab. I would say, we could better fold the info that are displayed before the table, and upon a button click unfold this part of the page.

**Comment by VincentGardeux** [comment]
Not following the idea here?

**Comment by fab-dav** [comment]
added a label aside the title of cards when the filter is on
