### ISSUE TITLE
API

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#45]
Could you describe the API fully (there is only the phentoypes for now) at https://dgrpool.epfl.ch/home/api
Specifically:
- https://dgrpool.epfl.ch/studies.json
- https://dgrpool.epfl.ch/phenotypes.json (with the option all, i.e. https://dgrpool.epfl.ch/phenotypes.json?all=1)
- https://dgrpool.epfl.ch/studies/43.json for each study
- https://dgrpool.epfl.ch/dgrp_lines.json and https://dgrpool.epfl.ch/dgrp_lines/230.json for each ones

**Comment by VincentGardeux** [comment]
Also:

**Comment by fab-dav** [comment]
Done.
Added useful links.
