### ISSUE TITLE
Sort GWAS results by p-value

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#48]
In 
- GWAS results. e.g. http://biccsrv3.epfl.ch:32786/phenotypes/2088/gwas_analysis
- Table gene, e.g. http://biccsrv3.epfl.ch:32786/genes
- Table variants e.g. http://biccsrv3.epfl.ch:32786/variants

**Comment by fab-dav** [comment]
Done
