### ISSUE TITLE
Gene enrichment results

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#49]
We need to display or link the gene enrichment results in the GWAS output.
Currently there are 2 buttons but they are not pointing to anything

![image](https://github.com/user-attachments/assets/4e0b801a-a6ad-471f-a432-f70485b1bb26)

**Comment by fab-dav** [comment]
Done

**Comment by VincentGardeux** [comment]
**2 points:**
- We originally discussed a popup table?
- Currently, this does not work for the output of the http://biccsrv3.epfl.ch:32786/check_pheno tool. Should w deactivate the buttons in this case?

**Comment by fab-dav** [comment]
We said as first approx we can just download the file and would be better to be able to be able to browse the results yes.
And it's implemented for the moment only for the phenotypes.

**Comment by fab-dav** [comment]
now done also for the check_pheno tool

**Comment by VincentGardeux** [comment]
The files are not generated. We should remove the buttons for the Check pheno tool

**Comment by VincentGardeux** [comment]
TODO in the future: add a better preview of the files
