### ISSUE TITLE
PheWAS button in the "Check your phenotype" tool

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#5]
This button does not work in the results of a Check your phenotype tool.
Should we remove it? Or can we compute it?

**Comment by fab-dav** [comment]
This button works. I don't know if there was a bug before but at least in the current version, it's functional.

**Comment by VincentGardeux** [comment]
It works indeed.
Could you just sort the results by increasing p-value?
