### ISSUE TITLE
Add new GWAS calculation in the Tool "Check your phenotype"

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#50]
In http://biccsrv3.epfl.ch:32786/check_pheno
We need to add the new GWAS calculation.

Also, we need to add the gene enrichment results.
We have two options:
- 1. Keeping it within the main R script (it makes a system call to a Python script). This will increase a lot the time it takes to run.
- 2. Getting it out of the main R script. Then the script will still take ~1mn30 to run, but then we need to call the 2 Python scripts outside. And make sure we don't overload the server...

**Comment by VincentGardeux** [comment]
To check:
- list of required R packages: data.table, stringr, ramwas, car, rstatix, Cairo, jsonlite
- Default value for param 7: 0.2
- Default value for param 8: 0.01
- New param at pos 9: filtering p-value threshold. Should be 0.001 by default. The old optional param that was at pos 9 is now at pos 10
- Categorical phenotypes should now fail with an error message
- Output covariate file should now contain Shapiro + Kruskal results
- Output JSON file should now contain the exact command line that is ran: command_line_gwas. We should maybe display it somewhere?
- I now use CairoPDF for generating the PDFs. They should be less bugged.
- I now generate two output files for the GWAS: `*.fdr.annot.tsv.gz` containing all results (in JSON hash `plink_output_file`) and `.top_{filtering_pval}.annot.tsv.gz` containing the filtered results, at p-value threshold in param 9 (in JSON hash `plink_filtered_output_file`)

**Comment by fab-dav** [comment]
#6. [Required] Number of threads                                                                                                                                                                            
#7. [Required] Minimum genotyping ratio                                                                                                                                                                     
#8. [Required] Minimum MAF                                                                                                                                                                                  
#9. [Required] Filtering threshold for p-value
