### ISSUE TITLE
Add "Estimated Time Remaining" for the Tools

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#6]
When running a tool (GWAS / Correlation) on a user's dataset, there is already the position in the queue.
Maybe we could add an estimated waiting time or something like that? By counting ~1mn30s for each run.

**Comment by fab-dav** [comment]
I've added this wait estimation. Also removed the 2 tabs with the 0 while the results are not yet ready.

**Comment by VincentGardeux** [comment]
The tool is not working anymore? I tried with this file
[download.txt](https://github.com/user-attachments/files/15792181/download.txt)

**Comment by fab-dav** [comment]
ah yes, I was still woking on something else...

**Comment by fab-dav** [comment]
Can you try again this?

**Comment by VincentGardeux** [comment]
Still buggy

**Comment by fab-dav** [comment]
Please stop to send messages about the tool, I'm working on it now

**Comment by fab-dav** [comment]
You can test this again
