### ISSUE TITLE
GWAS Boxplot

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#7]
In the results of GWAS, we have the boxplot button, which shows 2 boxplots.
It would be better if the REF boxplot would always be on the left, and the ALT on the right

**Comment by fab-dav** [comment]
Fixed. I also removed the legend on the top right corner of the plot, because it was not bringing anything more than the labels of the 2 box plots and even is problematic in the case of big indels by shrinking the plots.
