### ISSUE TITLE
Tools bug with certain files

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#8]
In the Tools section. If I upload this file, it fails silently, blocking everything

```
TF	target	importance
bi	lncRNA:CR32773	860.1348758949149
CG34354	trv	453.3228382892794
br	Mur2B	423.2655614298533
ara	caup	400.6674918995693
trv	CG34354	383.86931035708113
salr	salm	352.6318352774896
```

**Comment by VincentGardeux** [comment]
Of course this file makes no sense. But it should display an error message.

**Comment by fab-dav** [comment]
OK, it fails because indeed it makes absolutely no sense. I'm expecting to have at least a column with DGRP lines. Will check this as well.

**Comment by fab-dav** [comment]
Done
