### ISSUE TITLE
PheWAS results do not display uncurated datasets

### ISSUE THREAD

**Issue by VincentGardeux** [DeplanckeLab/dgrpool_web#9]
In the PheWAS results, we see different studies. But only curated studies.
We should add a checkbox to allow for any study.

Same feature than the one we have at the top of the [https://dgrpool.epfl.ch/phenotypes](https://dgrpool.epfl.ch/phenotypes) page

**Comment by fab-dav** [comment]
I think here it's better to stick to curated studies. To add a choice will only add some confusion.

**Comment by fab-dav** [comment]
load all studies and filter in js

**Comment by VincentGardeux** [comment]
Il y a tjr un pb avec les scroll bars:
![image](https://github.com/user-attachments/assets/99ce6510-5a39-47f2-abe5-5abec7875ca9)
Ici pour http://biccsrv3.epfl.ch:32786/phenotypes/2088/gwas_analysis

Sinon, il faudrait cocher le curated studies par défaut (comme dans le reste du site).
Et le bouton obsolete est useless, il faut toujours filtrer les obsolete.

**Comment by VincentGardeux** [comment]
> Sinon, il faudrait cocher le curated studies par défaut (comme dans le reste du site).
> Et le bouton obsolete est useless, il faut toujours filtrer les obsolete.

**Comment by VincentGardeux** [comment]
**Left to do:**
- biccsrv3.epfl.ch:32786/phenotypes Curated studies should be checked by default (it was the case before)
- In phewas results: Curated studies should be checked by default
- In phewas results: obsolete button should be removed. All obsolete values should NOT be displayed.

**Comment by fab-dav** [comment]
check box "exclude obsolete phenotypes" removed

**Comment by fab-dav** [comment]
from what I can see in the code, the curated studies checkbox is checked by default

**Comment by VincentGardeux** [comment]
It is now the case for the PheWAS button. Not for http://biccsrv3.epfl.ch:32786/phenotypes

**Comment by fab-dav** [comment]
OK, I understood what was wrong and corrected it.
